name: bmprogresshud
description: the loading hud widget. like SVProgressHUD in iOS, easy to use
version: 1.0.3
homepage: https://github.com/zhengbomo/bmprogresshud

environment:
  sdk: ">=2.12.0-0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
